/* Shared UI primitives: Icon, Btn, Rating — ported 1:1 from the approved mockup app.jsx */
import React from 'react'
import { STRINGS } from '../lib/data.js'
import {
  ShoppingBag, Sparkles, ArrowRight, Star, Flame, Plus, X, ShieldCheck, Sprout, Smile,
  ChevronsRight, ChevronsLeft, Bell, Image, Heart, Leaf, CheckCircle2, Wheat, Candy,
  Droplet, XCircle, MapPin, Phone, Mail, Send, Trash2, Menu, MessageCircle,
  FlaskConical, Palette, Pill, Feather, Ban, Zap, BadgeCheck, CandyOff, Users, Eye,
  ScanLine, ChevronDown, MessageCircleQuestion,
} from 'lucide-react'

/* Pinned lucide-react set (handoff doc 03: Lucide, stroke 2–2.2, navy). */
const ICONS = {
  'shopping-bag': ShoppingBag,
  sparkles: Sparkles,
  'arrow-right': ArrowRight,
  star: Star,
  flame: Flame,
  plus: Plus,
  x: X,
  'shield-check': ShieldCheck,
  sprout: Sprout,
  smile: Smile,
  'chevrons-right': ChevronsRight,
  'chevrons-left': ChevronsLeft,
  bell: Bell,
  image: Image,
  heart: Heart,
  leaf: Leaf,
  'check-circle-2': CheckCircle2,
  wheat: Wheat,
  candy: Candy,
  droplet: Droplet,
  'x-circle': XCircle,
  'map-pin': MapPin,
  phone: Phone,
  mail: Mail,
  send: Send,
  'trash-2': Trash2,
  menu: Menu,
  'message-circle': MessageCircle,
  'flask-conical': FlaskConical,
  palette: Palette,
  pill: Pill,
  feather: Feather,
  ban: Ban,
  zap: Zap,
  'badge-check': BadgeCheck,
  'candy-off': CandyOff,
  users: Users,
  eye: Eye,
  'scan-line': ScanLine,
  'chevron-down': ChevronDown,
  'message-circle-question': MessageCircleQuestion,
}

/* Focus trap for dialogs (design-critique M5, handoff doc 06 R10).
   Call with a ref to the dialog panel and whether it's open: moves focus in on open,
   keeps Tab cycling inside, restores focus to the opener on close. */
export function useFocusTrap(panelRef, active) {
  React.useEffect(() => {
    if (!active || !panelRef.current) return
    const panel = panelRef.current
    const prev = document.activeElement
    const focusables = () => [...panel.querySelectorAll('button, [href], input, textarea, select, [tabindex]:not([tabindex="-1"])')].filter((el) => !el.disabled && el.offsetParent !== null)
    const first = focusables()[0]
    if (first) first.focus()
    const onKey = (e) => {
      if (e.key !== 'Tab') return
      const els = focusables()
      if (!els.length) return
      const a = els[0]
      const z = els[els.length - 1]
      if (e.shiftKey && document.activeElement === a) { e.preventDefault(); z.focus() }
      else if (!e.shiftKey && document.activeElement === z) { e.preventDefault(); a.focus() }
    }
    panel.addEventListener('keydown', onKey)
    return () => {
      panel.removeEventListener('keydown', onKey)
      if (prev && prev.focus) prev.focus()
    }
  }, [active])
}

/* Spanish form-validation messages (issue 6). The browser's native validation bubble
   follows the browser UI locale, not lang="es", so we override the message per field.
   Spread onto required inputs: <input required {...esValidation('email')} /> */
export function esValidation(kind = 'text') {
  return {
    onInvalid: (e) => {
      const el = e.target
      const F = STRINGS.forms
      if (el.validity.valueMissing) el.setCustomValidity(kind === 'email' ? F.requiredEmail : F.requiredField)
      else if (el.validity.typeMismatch) el.setCustomValidity(F.invalidEmail)
      else el.setCustomValidity('')
    },
    onInput: (e) => e.target.setCustomValidity(''),
  }
}

/* Responsive image (design-critique H2). Takes the data file's .png path and derives
   AVIF/WebP srcset variants generated by scripts/optimize-images.mjs:
     <base>-<w>.avif / <base>-<w>.webp + <base>.png fallback.
   Always sets width/height (CLS) and lazy-loads unless eager. */
export function PumImg({ src, widths = [200, 400, 800], sizes = '100vw', alt = '', width, height, eager = false, fetchPriority, style, imgRef, className, imgProps = {} }) {
  const base = src.replace(/\.(png|webp|avif)$/i, '').replace(/-\d+$/, '')
  const set = (ext) => widths.map((w) => `${base}-${w}.${ext} ${w}w`).join(', ')
  return (
    /* display:contents — the picture must not create a box, or the img's percentage
       max-width/width would resolve against the picture itself (double-shrinking it
       inside flex/grid parents) instead of the real layout container. */
    <picture style={{ display: 'contents' }}>
      <source type="image/avif" srcSet={set('avif')} sizes={sizes} />
      <source type="image/webp" srcSet={set('webp')} sizes={sizes} />
      <img
        ref={imgRef}
        src={`${base}.png`}
        alt={alt}
        width={width}
        height={height}
        loading={eager ? 'eager' : 'lazy'}
        decoding={eager ? 'sync' : 'async'}
        fetchpriority={fetchPriority}
        className={className}
        style={style}
        {...imgProps}
      />
    </picture>
  )
}

/* Deck target nutrition table (T0.2): per 30 g / per 100 g / NOM-051 limit + footnote.
   Data from flavors.json `nutrition`. Used on flavor pages, the product modal, and
   the ingredientes page so the published facts match the distributor deck exactly. */
export function NutritionTable({ data, compact = false }) {
  const th = { fontFamily: 'var(--font-display)', fontWeight: 800, fontSize: compact ? 11 : 12, padding: compact ? '7px 8px' : '8px 12px', textAlign: 'right', whiteSpace: 'nowrap' }
  const td = { fontSize: compact ? 12 : 13, fontWeight: 600, padding: compact ? '6px 8px' : '7px 12px', textAlign: 'right', whiteSpace: 'nowrap', color: 'var(--pum-navy)' }
  const labelTd = { ...td, textAlign: 'left', color: 'var(--fg-soft)', whiteSpace: 'normal' }
  return (
    <div>
      <div style={{ border: '2px solid var(--pum-navy)', borderRadius: 16, overflow: 'hidden' }}>
        <div style={{ background: 'var(--pum-navy)', color: 'var(--pum-cream)', padding: compact ? '8px 12px' : '8px 14px', fontFamily: 'var(--font-display)', fontWeight: 800, fontSize: 14, display: 'flex', justifyContent: 'space-between', gap: 10 }}>
          <span>{data.title}</span><span style={{ opacity: 0.7 }}>{data.portion}</span>
        </div>
        <div style={{ overflowX: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', background: 'var(--pum-cream)' }}>
            <thead>
              <tr>
                {data.headers.map((h, i) => <th key={i} style={{ ...th, textAlign: i === 0 ? 'left' : 'right', color: 'var(--fg-mute)', borderBottom: '1px solid var(--border)' }}>{h}</th>)}
              </tr>
            </thead>
            <tbody>
              {data.rows.map((r, i) => (
                <tr key={i} style={{ background: i % 2 ? 'transparent' : 'rgba(255,255,255,.55)' }}>
                  <td style={{ ...labelTd, borderTop: '1px solid var(--border)' }}>{r[0]}</td>
                  <td style={{ ...td, fontWeight: 800, borderTop: '1px solid var(--border)' }}>{r[1]}</td>
                  <td style={{ ...td, borderTop: '1px solid var(--border)' }}>{r[2]}</td>
                  <td style={{ ...td, color: 'var(--fg-mute)', borderTop: '1px solid var(--border)' }}>{r[3]}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
      <p style={{ fontSize: 11.5, color: 'var(--fg-mute)', fontWeight: 600, margin: '8px 2px 0', lineHeight: 1.45 }}>*{data.footnote}</p>
    </div>
  )
}

/* Inline-markdown renderer for the verbatim brand copy (PUM_ClaudeDesign_build_prompt.md).
   Handles [label](/route) links, **bold** and *italic*. Markdown routes from the copy
   (/ingredientes, /para-papas, /sabores/x, /preguntas-frecuentes) are mapped to the real
   built .html routes so the approved copy can be pasted verbatim into the data files. */
const ROUTE_MAP = {
  '/ingredientes': '/marca/ingredientes.html',
  '/para-papas': '/marca/nosotros.html',
  '/preguntas-frecuentes': '/preguntas-frecuentes.html',
}
export function resolveHref(href) {
  if (ROUTE_MAP[href]) return ROUTE_MAP[href]
  if (/^\/sabores\/[a-z]+$/i.test(href)) return `${href}.html`
  return href
}
function emphasis(str, kp) {
  const out = []
  const re = /\*\*([^*]+)\*\*|\*([^*]+)\*/g
  let m, last = 0, k = 0
  while ((m = re.exec(str))) {
    if (m.index > last) out.push(str.slice(last, m.index))
    if (m[1] != null) out.push(<strong key={`${kp}b${k++}`}>{m[1]}</strong>)
    else out.push(<em key={`${kp}i${k++}`}>{m[2]}</em>)
    last = re.lastIndex
  }
  if (last < str.length) out.push(str.slice(last))
  return out
}
export function inlineMd(text, kp = 't') {
  if (text == null) return null
  const out = []
  const re = /\[([^\]]+)\]\(([^)]+)\)/g
  let m, last = 0, k = 0
  while ((m = re.exec(text))) {
    if (m.index > last) out.push(...emphasis(text.slice(last, m.index), `${kp}p${k}`))
    out.push(<a key={`${kp}l${k++}`} className="inl" href={resolveHref(m[2])}>{emphasis(m[1], `${kp}la${k}`)}</a>)
    last = re.lastIndex
  }
  if (last < text.length) out.push(...emphasis(text.slice(last), `${kp}e`))
  return out
}
export function RichText({ text, as: Tag = 'p', className, style }) {
  return <Tag className={className} style={style}>{inlineMd(text)}</Tag>
}

/* Generic content table for the Ingredientes page (cells may contain inline-markdown
   links). Horizontally scrolls on narrow screens via the .table-wrap wrapper. */
export function MdTable({ headers, rows }) {
  return (
    <div className="table-wrap">
      <table className="prose-table">
        <thead><tr>{headers.map((h, i) => <th key={i}>{h}</th>)}</tr></thead>
        <tbody>
          {rows.map((r, i) => (
            <tr key={i}>{r.map((c, j) => <td key={j}>{inlineMd(c, `c${i}-${j}-`)}</td>)}</tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

export function Icon({ name, size = 22, stroke = 2.2, color, style }) {
  const Cmp = ICONS[name]
  if (!Cmp) return null
  return <Cmp size={size} strokeWidth={stroke} color={color || 'currentColor'} style={{ display: 'inline-flex', flexShrink: 0, ...style }} aria-hidden="true" />
}

export function Btn({ children, variant = 'primary', size = 'md', onClick, style, type }) {
  const [st, setSt] = React.useState('')
  const base = { fontFamily: 'var(--font-display)', fontWeight: 800, border: 'none', borderRadius: 999, cursor: 'pointer', letterSpacing: '.01em', display: 'inline-flex', alignItems: 'center', gap: 9, lineHeight: 1, fontSize: size === 'lg' ? 19 : 16, padding: size === 'lg' ? '15px 30px' : '12px 24px', transition: 'transform .12s cubic-bezier(.34,1.56,.64,1),box-shadow .12s,filter .12s', ...style }
  const skins = {
    primary: { background: 'var(--pum-corn)', color: 'var(--pum-navy)', boxShadow: '0 4px 0 var(--pum-corn-deep)' },
    secondary: { background: 'var(--pum-navy)', color: 'var(--pum-cream)', boxShadow: '0 4px 0 #050d1d' },
    ghost: { background: 'transparent', color: 'var(--pum-navy)', boxShadow: 'inset 0 0 0 2.5px var(--pum-navy)' },
    light: { background: '#fff', color: 'var(--pum-navy)', boxShadow: '0 4px 0 rgba(0,0,0,.18)' },
  }
  const press = variant !== 'ghost'
  const dyn = st === 'press' && press ? { transform: 'translateY(4px)', boxShadow: '0 0 0 transparent' } : st === 'hover' ? { transform: 'translateY(-2px)', filter: 'brightness(1.04)' } : {}
  return (
    <button type={type} onClick={onClick} onMouseEnter={() => setSt('hover')} onMouseLeave={() => setSt('')} onMouseDown={() => setSt('press')} onMouseUp={() => setSt('hover')} style={{ ...base, ...skins[variant], ...dyn }}>
      {children}
    </button>
  )
}

export function Rating({ value, label, fill = 'var(--pum-navy)', track = 'rgba(255,255,255,.5)', ink = 'var(--pum-navy)' }) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
      <span style={{ fontSize: 11, fontWeight: 800, letterSpacing: '.06em', textTransform: 'uppercase', color: ink, opacity: 0.7, width: 82 }}>{label}</span>
      <div style={{ display: 'flex', gap: 3 }}>
        {[1, 2, 3, 4, 5].map((i) => <span key={i} style={{ width: 13, height: 13, borderRadius: i <= value ? 4 : '50%', background: i <= value ? fill : track, transition: 'all .2s' }} />)}
      </div>
    </div>
  )
}
